using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MultiDeviceAIO
{
    //#CHECK
    [Serializable]
    public class AIODeviceException : Exception
    {
        public long code { get; } = 0;

        public AIODeviceException(string message) : base(message) {}

        public AIODeviceException(long code) : base(AIOERRORCODES(code))
        {
            this.code = code;
        }

        /* Handleable Errors:
         * 
         * 7: reset devices
         * 
         */

        private static string AIOERRORCODES(long code)
        {
            switch (code)
            {
                case 0: return "Normality completion"; 
                case 1: return "Failed in the acquisition of the resource. When you install the hardware, the resource of I/O address, interrupt level cannot be retrieved. Check the resource in Device Manager"; 
                case 2: return "Failed in the registration of the interruption routine. The device may be being used by such another driver as API-AIO.. Please remove other drivers by using Device Manager.. And, if the device is with interrupt jumper, please do the necessary settings"; 
                case 3: return "Failed in the allocation of the memory. Memory is insufficient. Terminate the unnecessary applications"; 
                case 4: return "Failed in the access of registry. Please contact CONTEC Information Center"; 
                case 5: return "The value of Address is unusual at the time of bus-master registration. Please contact CONTEC Information Center"; 
                case 6: return "Failed in the creation of the adapter object. Please contact CONTEC Information Center"; 
                case 7: return "Execute AioResetDevice function because the device has recovered from standby mode";
                case 10000: return "The device name which wasn't registered by a device manager was specified. Specify the right device name"; 
                case 10001: return "Invalid ID was specified. Please use the ID retrieved from AioInit to specify the ID in function"; 
                case 10002: return "AIO driver can't be called. At first, perform the function AioInit"; 
                case 10003: return "Failed in the creation of the file. Please confirm whether the device driver has been started up normally in Device Manager.. If the device driver has not been started up normally, delete the device from Device Manager, and recognize the device again"; 
                case 10004: return "Failed in the closing of the file. There is a possibility that you performed termination processing for a device which was not initialized.  This error may be ignored"; 
                case 10005: return "Failed in the creation of the thread. Please contact CONTEC Information Center"; 
                case 10006: return "Device not found. Make sure that the device is registered in device manager"; 
                case 10007: return "Pointer to DeviceName is NULL"; 
                case 10008: return "Pointer to Device is NULL"; 
                case 10009: return "Device not found. Make sure that the device is registered in device manager"; 
                case 10010: return "Pointer to DeviceName is NULL"; 
                case 10011: return "Pointer to Device is NULL"; 
                case 10012: return "Pointer to BoardId is NULL"; 
                case 10013: return "Could not get device type"; 
                case 10014: return "Pointer to Device is NULL"; 
                case 10015: return "Pointer to DeviceType is NULL"; 
                case 10100: return "A device name isn't stored in DeviceName. The string DeviceName is empty. Please store the device name into it"; 
                case 10101: return "Pointer to Id is NULL. Specify the address of variable to parameter"; 
                case 10180: return "Pointer to ErrorString is NULL. Specify the address of variable to parameter"; 
                case 10220: return "The value of Offset is a minus. Specify a positive number to Offset"; 
                case 10221: return "Pointer to Data is NULL. Specify the address of variable to parameter"; 
                case 10222: return "The value of Flag is outside the designated range of the function"; 
                case 10240: return "The value of Offset is a minus. Specify a positive number to Offset"; 
                case 10241: return "Pointer to Data is NULL. Specify the address of variable to parameter"; 
                case 10242: return "The value of Flag is outside the designated range of the function"; 
                case 10260: return "The value of Offset is a minus. Specify a positive number to Offset"; 
                case 10261: return "Pointer to Data is NULL. Specify the address of variable to parameter"; 
                case 10262: return "The value of Flag is outside the designated range of the function"; 
                case 10280: return "The value of Offset is a minus. Specify a positive number to Offset"; 
                case 10281: return "The value of Flag is outside the designated range of the function"; 
                case 10300: return "The value of Offset is a minus. Specify a positive number to Offset"; 
                case 10301: return "The value of Flag is outside the designated range of the function"; 
                case 10320: return "The value of Offset is a minus. Specify a positive number to Offset"; 
                case 10321: return "The value of Flag is outside the designated range of the function"; 
                case 10340: return "The value of Signal is outside the designated range of the function"; 
                case 10341: return "The value of Value is outside the designated range of the function"; 
                case 10350: return "The value of Signal is outside the designated range of the function"; 
                case 10351: return "Pointer to Value is NULL"; 
                case 11000: return "The value of AiInputMethod is outside the designated range of the function. Set 0(single end input) or 1(differential input) to AiInputMethod"; 
                case 11010: return "Pointer to AiInputMethod is NULL. Specify the address of variable to parameter"; 
                case 11020: return "The value of AiChannels is outside the designated range of the function. Specify the number of analog input channels in range: 1 <= AiChannels <= Max number of channels"; 
                case 11030: return "Pointer to AiChannels is NULL. Specify the address of variable to parameter"; 
                case 11040: return "The value of AiChennal is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 11041: return "The value of AiRange is outside the designated range of the function"; 
                case 11050: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 11051: return "Pointer to AiRange is NULL. Specify the address of variable to parameter"; 
                case 11060: return "The value of AiRange is outside the designated range of the function"; 
                case 11080: return "The value of AiMemoryType is outside the designated range of the function. Set 0(FIFO) or 1(RING) to AiMemoryType"; 
                case 11090: return "Pointer to AiMemoryType is NULL. Specify the address of variable to parameter"; 
                case 11100: return "The value of AiRepeatTimes is outside the designated range of the function. AiRepeatTimes should be set to a value greater than or equal to 0"; 
                case 11110: return "Pointer to AiRepeatTimes is NULL. Specify the address of variable to parameter"; 
                case 11120: return "The value of AiClockType is outside the designated range of the function. Set 0(clock for conversion) or 1(external clock) to AiClockType"; 
                case 11130: return "Pointer to AiClockType is NULL. Specify the address of variable to parameter"; 
                case 11140: return "The value of AiSamplingClock is outside the designated range of the function. AiSamplingClock should be set to a value greater than or equal to 1"; 
                case 11150: return "Pointer to AiSamplingClock is NULL. Specify the address of variable to parameter"; 
                case 11160: return "The value of AiStartTrigger is outside the designated range of the function"; 
                case 11170: return "Pointer to AiStartTrigger is NULL. Specify the address of variable to parameter"; 
                case 11180: return "The value of AiChennal is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 11181: return "The value of AiDirection is outside the designated range of the function. Set 0(both sides), 1(rising) or 2(falling) to AiDirection"; 
                case 11190: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <=AiChannel <= Max channel"; 
                case 11191: return "Pointer to AiStartLevel is NULL. Specify the address of variable to parameter"; 
                case 11192: return "Pointer to AiDirection is NULL. Specify the address of variable to parameter"; 
                case 11260: return "The value of AiStopTrigger is outside the designated range of the function. Specify the condition for stopping conversion in range: 0 <= AiStopTrigger <= 4"; 
                case 11270: return "Pointer to AiStopTrigger is NULL. Specify the address of variable to parameter"; 
                case 11280: return "The value of AiStopTimes is outside the designated range of the function. AiStopTimes should be set to a value greater than or equal to 1"; 
                case 11290: return "Pointer to AiStopTimes is NULL. Specify the address of variable to parameter"; 
                case 11300: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 11301: return "The value of AiDirection is outside the designated range of the function. Set 0(both sides), 1(rising) or 2(falling) to AiDirection"; 
                case 11310: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 11311: return "Pointer to AiStopLevel is NULL. Specify the address of variable to parameter"; 
                case 11312: return "Pointer to AiDirection is NULL. Specify the address of variable to parameter"; 
                case 11360: return "The value of AiStopDelayTimes is outside the designated range of the function. AiStopDelayTimes should be set to a value greater than or equal to 0"; 
                case 11370: return "Pointer to AiStopDelayTimes is NULL. Specify the address of variable to parameter"; 
                case 11390: return "Pointer to AiEvent is NULL. Specify the address of variable to parameter"; 
                case 11400: return "The value of AiSamplingTimes is outside the designated range of the function. AiSamplingTimes should be set to a value greater than or equal to 0"; 
                case 11410: return "Pointer to AiSamplingTimes is NULL. Specify the address of variable to parameter"; 
                case 11420: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 11421: return "Pointer to AiData is NULL. Specify the address of variable to parameter"; 
                case 11440: return "The value of AiChannels is outside the designated range of the function. Specify the number of channels setting in range: 1 <= AiChannels <= Max number of channels"; 
                case 11441: return "Pointer to AiData is NULL. Specify the address of variable to parameter"; 
                case 11460: return "The thread can't be carried out"; 
                case 11480: return "A driver inner error occurred"; 
                case 11481: return "A driver inner error occurred"; 
                case 11482: return "A driver inner error occurred"; 
                case 11483: return "A driver inner error occurred"; 
                case 11500: return "Pointer to AiStatus is NULL. Specify the address of variable to parameter"; 
                case 11520: return "Pointer to AiSamplingCount is NULL. Specify the address of variable to parameter"; 
                case 11540: return "Pointer to AiRepeatCount is NULL. Specify the address of variable to parameter"; 
                case 11560: return "Pointer to AiStopTriggerCount is NULL. Specify the address of variable to parameter"; 
                case 11580: return "Pointer to AiSamplingTimes is NULL. Specify the address of variable to parameter"; 
                case 11581: return "Pointer to AiData is NULL. Specify the address of variable to parameter"; 
                case 11720: return "Pointer to AiMaxChannels is NULL. Specify the address of variable to parameter"; 
                case 11740: return "Pointer to AiResolution is NULL. Specify the address of variable to parameter"; 
                case 11760: return "The value of AiChannel is outside the designated range of the function. Specify the analog input channel in range: 0 <= AiChannel <= Max channel"; 
                case 11761: return "The value of Sequence is outside the designated range of the function. Specify the order for channels to convert in range: 0 <= AiChannel <= Max channel"; 
                case 11770: return "The value of AiChannel is outside the designated range of the function. Specify the analog input channel in range: 0 <= AiChannel <= Max channel"; 
                case 11771: return "Pointer to Sequence is NULL. Specify the address of variable to parameter"; 
                case 11820: return "The value of AiMemorysize is outside the designated range of the function"; 
                case 11830: return "Pointer to AiMemorySize is NULL"; 
                case 11840: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 11841: return "Pointer to AiData is NULL. Specify the address of variable to parameter"; 
                case 11860: return "The value of AiChannels is outside the designated range of the function. Specify the number of channels setting in range: 1 <= AiChannels <= Max number of channels"; 
                case 11861: return "Pointer to AiData is NULL. Specify the address of variable to parameter"; 
                case 11880: return "Pointer to AiSamplingTimes is NULL. Specify the address of variable to parameter"; 
                case 11881: return "Pointer to AiData is NULL. Specify the address of variable to parameter"; 
                case 11920: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 11921: return "The value of AiDirection is outside the designated range of the function"; 
                case 11930: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 11931: return "Pointer to AiStartLevel is NULL. Specify the address of variable to parameter"; 
                case 11932: return "Pointer to AiDirection is NULL"; 
                case 11940: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 11941: return "The value of AiDirection is outside the designated range of the function"; 
                case 11950: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 11951: return "Pointer to AiStopLevel is NULL. Specify the address of variable to parameter"; 
                case 11952: return "Pointer to AiDirection is NULL. Specify the address of variable to parameter"; 
                case 11960: return "The value of AiTransferMode is outside the designated range of the function"; 
                case 11970: return "Pointer to AiTransferMode is NULL. Specify the address of variable to parameter"; 
                case 11980: return "The value of DataNumber is outside the designated range of the function"; 
                case 11981: return "Pointer to Buffer is NULL. Specify the address of variable to parameter"; 
                case 11982: return "It failed in securing a buffer for Bus-Master transfer"; 
                case 12020: return "Pointer to DataSize is NULL. Specify the address of variable to parameter"; 
                case 12040: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 12041: return "The value of StateTimes is outside the designated range of the function"; 
                case 12050: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 12051: return "Pointer to Level1 is NULL. Specify the address of variable to parameter"; 
                case 12052: return "Pointer to Level2 is NULL. Specify the address of variable to parameter"; 
                case 12053: return "Pointer to StateTimes is NULL. Specify the address of variable to parameter"; 
                case 12060: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 12061: return "The value of StateTimes is outside the designated range of the function"; 
                case 12070: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 12071: return "Pointer to Level1 is NULL. Specify the address of variable to parameter"; 
                case 12072: return "Pointer to Level2 is NULL. Specify the address of variable to parameter"; 
                case 12073: return "Pointer to StateTimes is NULL. Specify the address of variable to parameter"; 
                case 12080: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 12081: return "The value of StateTimes is outside the designated range of the function"; 
                case 12090: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 12091: return "Pointer to Level1 is NULL. Specify the address of variable to parameter"; 
                case 12092: return "Pointer to Level2 is NULL. Specify the address of variable to parameter"; 
                case 12093: return "Pointer to StateTimes is NULL. Specify the address of variable to parameter"; 
                case 12100: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 12101: return "The value of StateTimes is outside the designated range of the function"; 
                case 12110: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 12111: return "Pointer to Level1 is NULL. Specify the address of variable to parameter"; 
                case 12112: return "Pointer to Level1 is NULL. Specify the address of variable to parameter"; 
                case 12113: return "Pointer to StateTimes is NULL. Specify the address of variable to parameter"; 
                case 12120: return "The value of AiTransferTimes is outside the designated range of the function"; 
                case 12130: return "Pointer to AiTransferTimes is NULL. Specify the address of variable to parameter"; 
                case 12140: return "Pointer to AiTransferCount is NULL. Specify the address of variable to parameter"; 
                case 12160: return "Pointer to Lap is NULL. Specify the address of variable to parameter"; 
                case 12180: return "Pointer to Count is NULL. Specify the address of variable to parameter"; 
                case 12200: return "The value of Range is outside the designated range of the function"; 
                case 12201: return "The value of Type is outside the designated range of the function"; 
                case 12202: return "The value of Data is outside the designated range of the function"; 
                case 12003: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <=AiChannel <= Max channel"; 
                case 12210: return "The value of Range is outside the designated range of the function"; 
                case 12211: return "The value of Type is outside the designated range of the function"; 
                case 12212: return "Pointer to Data is NULL. Specify the address of variable to parameter"; 
                case 12213: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 12220: return "The value of Range is outside the designated range of the function"; 
                case 12221: return "The value of Type is outside the designated range of the function"; 
                case 12222: return "Pointer to Data is NULL. Specify the address of variable to parameter"; 
                case 12223: return "The value of AiChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AiChannel <= Max channel"; 
                case 12240: return "The value of AiScanClock is outside the designated range of the function"; 
                case 12250: return "Pointer to AiScanClock is NULL"; 
                case 12260: return "Pointer to AoSamplingClock is NULL"; 
                case 12310: return "The value of AiClockEdge is outside the designated range of the function"; 
                case 12320: return "Pointer to AiClockEdge is NULL"; 
                case 12382: return "Timeout occurred. Please reset the device, or extend the timeout period"; 
                case 13000: return "The value of AoChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AoChannel <= Max channel"; 
                case 13020: return "The value of AoChannels is outside the designated range of the function. Specify the number of analog output channels in range: 1 <= AoChannels <= Max number of channels"; 
                case 13021: return "Pointer to AoData is NULL. Specify the address of variable to parameter"; 
                case 13040: return "Pointer to AoResolution is NULL. Specify the address of variable to parameter"; 
                case 13060: return "The value of AoChannels is outside the designated range of the function. Specify the number of analog output channels in range: 1 <= AoChannels <= Max number of channels"; 
                case 13070: return "Pointer to AoChannels is NULL. Specify the address of variable to parameter"; 
                case 13080: return "Pointer to AoMaxChannels is NULL. Specify the address of variable to parameter"; 
                case 13100: return "The value of AoChannels is outside the designated range of the function. Specify the number of analog output channels in range: 1 <= AoChannels <= Max number of channels"; 
                case 13101: return "The value of AoRange is outside the designated range of the function"; 
                case 13110: return "The value of AoChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AoChannel <= Max channel"; 
                case 13111: return "Pointer to AoRange is NULL. Specify the address of variable to parameter"; 
                case 13120: return "The value of AoRange is outside the designated range of the function"; 
                case 13140: return "The value of AoMemoryType is outside the designated range of the function. Set 0(FIFO) or 1(RING) to AiMemoryType"; 
                case 13150: return "Pointer to AoMemoryType is NULL. Specify the address of variable to parameter"; 
                case 13160: return "The value of AoRepeatTimes is outside the designated range of the function. AoRepeatTimes should be set to a value greater than or equal to 0"; 
                case 13170: return "Pointer to AoRepeatTimes is NULL. Specify the address of variable to parameter"; 
                case 13180: return "The value of AoClockType is outside the designated range of the function. Set 0(clock for conversion) or 1(external clock) to AoClockType"; 
                case 13190: return "Pointer to AoClockType is NULL. Specify the address of variable to parameter"; 
                case 13200: return "The value of AoSamplingClock is outside the designated range of the function. AoSamplingClock should be set to a value greater than or equal to 1"; 
                case 13210: return "Pointer to AoSamplingClock is NULL. Specify the address of variable to parameter"; 
                case 13220: return "The value of AoSamplingTimes is outside the designated range of the function. AoSamplingClock should be set to a value greater than or equal to 1"; 
                case 13221: return "Pointer to AoData is NULL. Specify the address of variable to parameter"; 
                case 13230: return "Pointer to AoSamplingTimes is NULL. Specify the address of variable to parameter"; 
                case 13240: return "The value of AoStartTrigger is outside the designated range of the function"; 
                case 13250: return "Pointer to AoStartTrigger is NULL. Specify the address of variable to parameter"; 
                case 13260: return "The value of AoStopTrigger is outside the designated range of the function"; 
                case 13270: return "Pointer to AoStopTrigger is NULL. Specify the address of variable to parameter"; 
                case 13290: return "Pointer to AoEvent is NULL. Specify the address of variable to parameter"; 
                case 13300: return "The value of AoSamplingTimes is outside the designated range of the function. AoStopTimes should be set to a value greater than or equal to 1"; 
                case 13310: return "Pointer to AoSamplingTimes is NULL. Specify the address of variable to parameter"; 
                case 13320: return "The thread can't be carried out"; 
                case 13360: return "The value of AoChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AoChannel <= Max channel"; 
                case 13370: return "The value of AoChannel is outside the designated range of the function. Specify the channel setting in range: 0 <= AoChannel <= Max channel"; 
                case 13380: return "Pointer to AoStatus is NULL. Specify the address of variable to parameter"; 
                case 13400: return "Pointer to AoSamplingCount is NULL. Specify the address of variable to parameter"; 
                case 13420: return "Pointer to AoRepeatCount is NULL. Specify the address of variable to parameter"; 
                case 13480: return "The value of AoMemorySize is outside the designated range of the function"; 
                case 13490: return "Pointer to AoMemorySize is NULL"; 
                case 13500: return "The value of AoChannel is outside the designated range of the function"; 
                case 13520: return "The value of AoChannels is outside the designated range of the function"; 
                case 13540: return "The value of AoSamplingTimes is outside the designated range of the function"; 
                case 13541: return "Pointer to AoData is NULL"; 
                case 13580: return "The value of AoTransferMode is outside the designated range of the function"; 
                case 13590: return "Pointer to AoTransferMode is NULL"; 
                case 13600: return "The value of DataNumber is outside the designated range of the function"; 
                case 13601: return "Pointer to Buffer is NULL"; 
                case 13602: return "It failed in securing a buffer for Bus-Master transfer"; 
                case 13640: return "Pointer to DataSize is NULL"; 
                case 13660: return "The value of AoTransferTimes is outside the designated range of the function"; 
                case 13670: return "Pointer to AoSamplingTimes is NULL"; 
                case 13680: return "Pointer to AoTransferCount is NULL"; 
                case 13700: return "Pointer to Lap is NULL"; 
                case 13720: return "The value of Range is outside the designated range of the function"; 
                case 13721: return "The value of Type is outside the designated range of the function"; 
                case 13722: return "The value of Data is outside the designated range of the function"; 
                case 13723: return "The value of AoChannel is outside the designated range of the function"; 
                case 13730: return "The value of Range is outside the designated range of the function"; 
                case 13731: return "The value of Type is outside the designated range of the function"; 
                case 13732: return "Pointer to Data is NULL"; 
                case 13733: return "The value of AoChannel is outside the designated range of the function"; 
                case 13740: return "The value of Range is outside the designated range of the function"; 
                case 13741: return "The value of Type is outside the designated range of the function"; 
                case 13742: return "Pointer to Data is NULL"; 
                case 13743: return "The value of AoChannel is outside the designated range of the function"; 
                case 13760: return "Pointer to AoSamplingClock is NULL"; 
                case 13770: return "The value of AoClockEdge is outside the designated range of the function"; 
                case 13780: return "Pointer to AiClockEdge is NULL"; 
                case 14000: return "The value of DiBit is outside the designated range of the function. Specify the digital input bit in range: 0 <= DiBit <= Max bit"; 
                case 14001: return "Pointer to DiData is NULL. Specify the address of variable to parameter"; 
                case 14010: return "The value of DiPort is outside the designated range of the function. Specify the digital input port in range: 0 <= DiPort <= Max port"; 
                case 14011: return "Pointer to DiData is NULL. Specify the address of variable to parameter"; 
                case 14020: return "The value of DoBit is outside the designated range of the function. Specify the digital output bit in range: 0 <= DoBit <= Max bit"; 
                case 14021: return "The value of DoData is outside the designated range of the function"; 
                case 14030: return "The value of DoPort is outside the designated range of the function. Specify the digital output port in range: 0 <= DoPort <= Max port"; 
                case 14031: return "The value of DoData is outside the designated range of the function"; 
                case 14040: return "The value of Bit is outside the designated range of the function"; 
                case 14041: return "The value of Value is outside the designated range of the function"; 
                case 14050: return "The value of Bit is outside the designated range of the function"; 
                case 14051: return "Pointer to Value is NULL"; 
                case 15000: return "The value of CntChannel is outside the designated range of the function"; 
                case 15010: return "The value of CntChannel is outside the designated range of the function"; 
                case 15011: return "Pointer to CntMode is NULL"; 
                case 15020: return "The value of CntChannel is outside the designated range of the function"; 
                case 15021: return "The value of PresetNumber is outside the designated range of the function"; 
                case 15022: return "The value of Flag is outside the designated range of the function"; 
                case 15023: return "Pointer to PresetData is NULL"; 
                case 15040: return "The value of CntChannel is outside the designated range of the function"; 
                case 15041: return "The value of ComparisonNumber is outside the designated range of the function"; 
                case 15042: return "The value of Flag is outside the designated range of the function"; 
                case 15043: return "Pointer to PresetData is NULL"; 
                case 15060: return "The value of CntChannel is outside the designated range of the function"; 
                case 15061: return "The value of CntClockType is outside the designated range of the function"; 
                case 15070: return "The value of CntChannel is outside the designated range of the function"; 
                case 15071: return "Pointer to CntClockType is NULL"; 
                case 15080: return "The value of CntChannel is outside the designated range of the function"; 
                case 15090: return "The value of CntChannel is outside the designated range of the function"; 
                case 15091: return "Pointer to CntEvent is NULL"; 
                case 15100: return "The value of CntChannel is outside the designated range of the function"; 
                case 15120: return "The value of CntChannel is outside the designated range of the function"; 
                case 15121: return "The value of Signal is outside the designated range of the function"; 
                case 15122: return "The value of Value is outside the designated range of the function"; 
                case 15130: return "The value of CntChannel is outside the designated range of the function"; 
                case 15131: return "The value of Signal is outside the designated range of the function"; 
                case 15132: return "Pointer to Value is NULL"; 
                case 15140: return "The value of CntChannel is outside the designated range of the function"; 
                case 15141: return "The thread can't be carried out"; 
                case 15160: return "The value of CntChannel is outside the designated range of the function"; 
                case 15180: return "The value of CntChannel is outside the designated range of the function"; 
                case 15200: return "The value of CntChannel is outside the designated range of the function"; 
                case 15201: return "Pointer to CntStatus is NULL"; 
                case 15220: return "The value of CntChannel is outside the designated range of the function"; 
                case 15221: return "Pointer to Count is NULL"; 
                case 15240: return "The value of CntChannel is outside the designated range of the function"; 
                case 15260: return "Pointer to CntMaxChannels is NULL"; 
                case 16000: return "The value of TimerId is outside the designated range of the function"; 
                case 16010: return "The value of TimerId is outside the designated range of the function"; 
                case 16011: return "Pointer to TmEvent is NULL"; 
                case 16020: return "The value of TimerId is outside the designated range of the function"; 
                case 16040: return "The value of TimerId is outside the designated range of the function"; 
                case 16041: return "The value of Interval is outside the designated range of the function"; 
                case 16042: return "The thread can't be carried out"; 
                case 16060: return "The value of TimerId is outside the designated range of the function"; 
                case 16080: return "The value of TimerId is outside the designated range of the function"; 
                case 16100: return "The value of TimerId is outside the designated range of the function"; 
                case 16120: return "The value of TimerId is outside the designated range of the function"; 
                case 16121: return "Pointer to Lap is NULL"; 
                case 16140: return "The value of TimerId is outside the designated range of the function"; 
                case 16160: return "The value of TimerId is outside the designated range of the function"; 
                case 16161: return "The value of Wait is outside the designated range of the function"; 
                case 17000: return "The value of Destination is outside the designated range of the function"; 
                case 17001: return "The value of Source is outside the designated range of the function"; 
                case 17010: return "The value of Input is outside the designated range of the function"; 
                case 17011: return "Pointer to Output is NULL"; 
                case 18000: return "Invalid mode setting"; 
                case 18100: return "Invalid data buffer address"; 
                case 18200: return "Window handle is invalid"; 
                case 20000: return "It failed in memory allocation for the object preparation. Memory is insufficient. Terminate the unnecessary applications"; 
                case 20001: return "This function can't be used by this device. This function cannot be used in the device without this functionality"; 
                case 20002: return "Can not use while by another device works"; 
                case 20003: return "Can not use because another process is using the device. When another process is using the device, all functions except for those that support multi-process can not be performed"; 
                case 20020: return "CRC error"; 
                case 20021: return "Bit pack error"; 
                case 20022: return "Toggle mismatch"; 
                case 20023: return "Stall PID"; 
                case 20024: return "Device not responding"; 
                case 20025: return "PID check failure"; 
                case 20026: return "Unexpected PID"; 
                case 20027: return "Data overrun"; 
                case 20028: return "Data underrun"; 
                case 20029: return "Buffer overrun"; 
                case 20030: return "Buffer underrun"; 
                case 20031: return "Endpoint halted"; 
                case 20032: return "Not found device information"; 
                case 20033: return "Access denied"; 
                case 20034: return "Invalid handle"; 
                case 20035: return "It's need to upgrade the firmware"; 
                case 20036: return "It's need to upgrade the host driver"; 
                case 20037: return "It failed in USB transfer"; 
                case 20100: return "The number of processes met an upper limit. Up to 16 processes can be executed simultaneously"; 
                case 20160: return "It failed in the reset of the device"; 
                case 20161: return "It failed in the reset of the bus-master"; 
                case 20340: return "The value of Signal is outside the designated range of the device being used"; 
                case 20341: return "The value of Value is outside the designated range of the device being used"; 
                case 20350: return "The value of Signal is outside the designated range of the device being used"; 
                case 21000: return "An analog input method can't be established with the device being used. Device is without this functionality"; 
                case 21001: return "The value of AiInputMethod is different from JP value. Must set analog input method by JP on device"; 
                case 21020: return "It was set up by the number of maximum channels because it exceeded the number of maximum channels of the device. The setting is automatically changed to the maximum number of channels"; 
                case 21040: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 21041: return "The value of AiRange is outside the designated range of the device being used"; 
                case 21042: return "JP of the device must be set in unipolar. JP on device was set bipolar"; 
                case 21043: return "JP of the device must be set in bipolar. JP on device was set unipolar"; 
                case 21044: return "It failed in the setting of the range"; 
                case 21060: return "The value of AiRange is outside the designated range of the device being used"; 
                case 21061: return "JP of the device must be set in unipolar. JP on device was set bipolar"; 
                case 21062: return "JP of the device must be set in bipolar. JP on device was set unipolar"; 
                case 21063: return "It failed in the setting of the range"; 
                case 21080: return "The value of AiMemoryType is outside the designated range of the device being used"; 
                case 21120: return "The value of AiClockType is outside the designated range of the device being used"; 
                case 21140: return "The value of AiSamplingClock is outside the designated range of the device being used"; 
                case 21160: return "The value of AiStartTrigger is outside the designated range of the device being used"; 
                case 21180: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 21181: return "Data to establish in the 12 bits device are within the range of 0 to 4095"; 
                case 21182: return "Data to establish in the 16 bits device are within the range of 0 to 65535"; 
                case 21183: return "A resolution can't be acquired"; 
                case 21184: return "The value of AiDirection is outside the designated range of the device being used"; 
                case 21260: return "The value of AiStopTrigger is outside the designated range of the device being used"; 
                case 21300: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 21301: return "Data to establish in the 12 bits device are within the range of 0 to 4095"; 
                case 21302: return "Data to establish in the 16 bits device are within the range of 0 to 65535"; 
                case 21303: return "A resolution can't be acquired"; 
                case 21304: return "The value of AiDirection is outside the designated range of the device being used"; 
                case 21420: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 21421: return "AD conversion error occurred. Please contact CONTEC Information Center"; 
                case 21423: return "The channel which isn't being used for the conversion is specified"; 
                case 21440: return "AD conversion error occurred. Please contact CONTEC Information Center"; 
                case 21441: return "The number of conversion channels was exceeded. It is converted on the maximum channel"; 
                case 21460: return "Because sampling clock error occurs, you must reset a device"; 
                case 21461: return "Virtual memory can't be allocated. Memory is insufficient. Terminate the unnecessary applications"; 
                case 21462: return "Virtual memory can't be initialized. Please contact CONTEC Information Center"; 
                case 21463: return "In the software start, set up the repeat number in 1"; 
                case 21464: return "Failed in the creation of the driver thread. Please contact CONTEC Information Center"; 
                case 21466: return "A user buffer isn't set up"; 
                case 21469: return "Buffer overflow error occurred, you must reset a memory"; 
                case 21480: return "A conversion can't be stopped with this command, use AioResetDevice function"; 
                case 21481: return "It failed in the stop of master transfer"; 
                case 21520: return "It failed in the acquisition of the sampling times. Please contact CONTEC Information Center"; 
                case 21580: return "It tried to acquire data beyond the converted number. AiSamplingTimes is changed to the maximum value"; 
                case 21581: return "It failed in the acquisition of the address"; 
                case 21584: return "FIFO is empty"; 
                case 21585: return "It tried to acquire data beyond the memory size. AiSamplingTimes is changed to the maximum value"; 
                case 21760: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 21761: return "The value of Sequence is outside the designated range of the device being used"; 
                case 21770: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 21840: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 21841: return "AD conversion error occurred"; 
                case 21843: return "The channel which isn't being used for the conversion is specified"; 
                case 21860: return "AD conversion error occurred"; 
                case 21861: return "The number of conversion channels was exceeded. It is converted on the maximum channel"; 
                case 21880: return "The value of AiChannels is outside the designated range of the device being used"; 
                case 21881: return "It tried to acquire data beyond the converted number. AiSamplingTimes is changed to the maximum value"; 
                case 21882: return "It failed in the acquisition of the address"; 
                case 21885: return "FIFO is empty"; 
                case 21886: return "It tried to acquire data beyond the memory size. AiSamplingTimes is changed to the maximum value"; 
                case 21920: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 21921: return "The value of AiStartLevel is outside the designated range of the device being used"; 
                case 21922: return "A resolution can't be acquired"; 
                case 21923: return "The value of AiDirection is outside the designated range of the device being used"; 
                case 21930: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 21940: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 21941: return "The value of AiStopLevel is outside the designated range of the device being used"; 
                case 21942: return "A resolution can't be acquired"; 
                case 21943: return "The value of AiDirection is outside the designated range of the device being used"; 
                case 21950: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 21960: return "The value of AiTransferMode is outside the designated range of the device being used"; 
                case 21980: return "The value of DataNumber is outside the designated range of the device being used"; 
                case 21981: return "Failed in the lock of the memory"; 
                case 21982: return "Failed in allocation of temporary memory"; 
                case 21984: return "BusMaster parameter error"; 
                case 22040: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 22041: return "Data to establish in the 12 bits device are within the range of 0 to 4095"; 
                case 22042: return "Data to establish in the 16 bits device are within the range of 0 to 65535"; 
                case 22043: return "A resolution can't be acquired"; 
                case 22044: return "The value of StateTimes is outside the designated range of the device being used"; 
                case 22050: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 22060: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 22061: return "Data to establish in the 12 bits device are within the range of 0 to 4095"; 
                case 22062: return "Data to establish in the 16 bits device are within the range of 0 to 65535"; 
                case 22063: return "A resolution can't be acquired"; 
                case 22064: return "The value of StateTimes is outside the designated range of the device being used"; 
                case 22070: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 22080: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 22081: return "Data to establish in the 12 bits device are within the range of 0 to 4095"; 
                case 22082: return "Data to establish in the 16 bits device are within the range of 0 to 65535"; 
                case 22083: return "A resolution can't be acquired"; 
                case 22084: return "The value of StateTimes is outside the designated range of the device being used"; 
                case 22085: return "A driver inner error occurred"; 
                case 22090: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 22100: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 22101: return "Data to establish in the 12 bits device are within the range of 0 to 4095"; 
                case 22102: return "Data to establish in the 16 bits device are within the range of 0 to 65535"; 
                case 22103: return "A resolution can't be acquired"; 
                case 22104: return "The value of StateTimes is outside the designated range of the device being used"; 
                case 22105: return "A driver inner error occurred"; 
                case 22110: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 22120: return "The value of AiTransferTimes is outside the designated range of the device being used"; 
                case 22140: return "It failed in the acquisition of the transfer times"; 
                case 22160: return "It failed in the acquisition of the replacement times"; 
                case 22200: return "The value of Range is outside the designated range of the device being used"; 
                case 22201: return "The value of Type is outside the designated range of the device being used"; 
                case 22202: return "The value of Data is outside the designated range of the device being used"; 
                case 22220: return "The value of Range is outside the designated range of the device being used"; 
                case 22221: return "The value of Type is outside the designated range of the device being used"; 
                case 22222: return "It failed to load the calibration data"; 
                case 22223: return "A driver inner error occurred"; 
                case 22240: return "The value of AiScanClock is outside the designated range of the device being used"; 
                case 22241: return "A driver inner error occurred"; 
                case 22270: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 22271: return "The value of Level1/Level2 is outside the designated range of the device being used"; 
                case 22272: return "A resolution can't be acquired"; 
                case 22273: return "The value of StateTimes is outside the designated range of the device being used"; 
                case 22280: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 22290: return "The value of AiChannel is outside the designated range of the device being used"; 
                case 22291: return "The value of Level1/Level2 is outside the designated range of the device being used"; 
                case 22292: return "A resolution can't be acquired"; 
                case 22293: return "The value of StateTimes is outside the designated range of the device being used"; 
                case 22310: return "The value of AiClockEdge is outside the designated range of the device being used"; 
                case 23000: return "The value of AoChannel is outside the designated range of the device being used"; 
                case 23001: return "DA conversion error occurred"; 
                case 23002: return "Specify data to establish in AoData in the range of 0 to 4095"; 
                case 23003: return "Specify data to establish in AoData in the range of 0 to 65535"; 
                case 23020: return "DA conversion error occurred"; 
                case 23021: return "The number of conversion channels was exceeded. It is converted on the maximum channels"; 
                case 23022: return "Specify data to establish in AoData in the range of 0 to 4095"; 
                case 23023: return "Specify data to establish in AoData in the range of 0 to 65535"; 
                case 23060: return "It is converted on the maximum channel because it exceeds the number of maximum channels of the device"; 
                case 23100: return "The value of AoChannel is outside the designated range of the device being used"; 
                case 23101: return "The value of AoRange is outside the designated range of the device being used"; 
                case 23102: return "It failed in the setting of the range"; 
                case 23120: return "The value of AoRange is outside the designated range of the device being used"; 
                case 23121: return "It failed in the setting of the range"; 
                case 23140: return "The value of AoMemoryType is outside the designated range of the device being used"; 
                case 23161: return "Repeat function is only available when using RING memory"; 
                case 23180: return "The value of AoClockType is outside the designated range of the device being used"; 
                case 23200: return "The value of AoSamplingClock is outside the designated range of the device being used"; 
                case 23220: return "Output data exceed memory capacity"; 
                case 23221: return "Failed in the allocation of the memory"; 
                case 23240: return "The value of AoStartTrigger is outside the designated range of the device being used"; 
                case 23260: return "The value of AoStopTrigger is outside the designated range of the device being used"; 
                case 23320: return "Data aren't established, or memory can't be secured"; 
                case 23321: return "Data aren't established"; 
                case 23326: return "A user buffer isn't set up"; 
                case 23500: return "The value of AoChannel is outside the designated range of the device being used"; 
                case 23501: return "DA conversion error occurred"; 
                case 23520: return "DA conversion error occurred"; 
                case 23521: return "The number of conversion channels was exceeded. It is converted on the maximum channels"; 
                case 23540: return "Output data exceed memory capacity"; 
                case 23541: return "The value of AoStartTrigger is outside the designated range of the device being used"; 
                case 23580: return "The value of AoTransferMode is outside the designated range of the device being used"; 
                case 23600: return "The value of DataNumber is outside the designated range of the device being used"; 
                case 23601: return "Failed in the lock of the memory"; 
                case 23602: return "Failed in allocation of temporary memory"; 
                case 23741: return "Failed in loading calibration data"; 
                case 23770: return "The value of AoClockEdge is outside the designated range of the device being used"; 
                case 24000: return "The value of DiBit is outside the designated range of the device being used"; 
                case 24010: return "The value of DiPort is outside the designated range of the device being used"; 
                case 24020: return "The value of DoBit is outside the designated range of the device being used"; 
                case 24030: return "The value of DoPort is outside the designated range of the device being used"; 
                case 24040: return "The value of Bit is outside the designated range of the device being used"; 
                case 24041: return "The value of Value is outside the designated range of the device being used"; 
                case 24050: return "The value of Bit is outside the designated range of the device being used"; 
                case 25000: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25002: return "Operation mode 'preset count value load' is not enable"; 
                case 25003: return "Operation mode 'Comparison count value load' is not enable"; 
                case 25010: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25020: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25021: return "The value of PresetNumber is outside the designated range of the device being used"; 
                case 25040: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25041: return "The value of ComparisonNumber is outside the designated range of the device being used"; 
                case 25060: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25061: return "The value of CntClockType is outside the designated range of the device being used"; 
                case 25070: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25080: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25090: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25100: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25120: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25121: return "The value of Value is outside the designated range of the device being used"; 
                case 25122: return "A driver inner error occurred"; 
                case 25123: return "The value of Signal is outside the designated range of the device being used"; 
                case 25130: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25131: return "The value of Signal is outside the designated range of the function"; 
                case 25140: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25160: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25180: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25181: return "A driver inner error occurred"; 
                case 25200: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25220: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 25240: return "The value of CntChannel is outside the designated range of the device being used"; 
                case 26000: return "The value of TimerId is outside the designated range of the device being used"; 
                case 26010: return "The value of TimerId is outside the designated range of the device being used"; 
                case 26020: return "The value of TimerId is outside the designated range of the device being used"; 
                case 26040: return "The value of TimerId is outside the designated range of the device being used"; 
                case 26060: return "The value of TimerId is outside the designated range of the device being used"; 
                case 26080: return "The value of TimerId is outside the designated range of the device being used"; 
                case 26100: return "The value of TimerId is outside the designated range of the device being used"; 
                case 26120: return "The value of TimerId is outside the designated range of the device being used"; 
                case 26140: return "The value of TimerId is outside the designated range of the device being used"; 
                case 26160: return "The value of TimerId is outside the designated range of the device being used"; 
                case 27000: return "The value of Destination is outside the designated range of the device being used"; 
                case 27001: return "The value of Source is outside the designated range of the device being used"; 
                case 27002: return "An invalid connection"; 
                case 27010: return "The value of Destination is outside the designated range of the device being used"; 
                case 28000: return "Invalid mode setting"; 
                case 28001: return "Channel number is out of range"; 
                case 28010: return "Number of channels is out of range"; 
                case 28011: return "Counter value is out of range"; 
                case 28012: return "Compare register number is out of range"; 
                case 28020: return "Timer value is out of range"; 
                case 28021: return "The output logic of the control output signal is out of range"; 
                case 28022: return "The kind of hardware event is out of range"; 
                case 28030: return "The coefficient of one-shot pulse width is out of range"; 
                case 28031: return "The input logic of control input signal is out of range"; 
                case 28032: return "The output data is out of range";
                default:
                    return "Unknown error " + code;
            }
        }

    }
}
