namespace MultiDeviceAIO
{
    partial class Scope
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.npSurface = new NPlot.Windows.PlotSurface2D();
            this.SuspendLayout();
            // 
            // npSurface
            // 
            this.npSurface.AutoScaleAutoGeneratedAxes = false;
            this.npSurface.AutoScaleTitle = false;
            this.npSurface.BackColor = System.Drawing.SystemColors.GradientActiveCaption;
            this.npSurface.DateTimeToolTip = false;
            this.npSurface.Legend = null;
            this.npSurface.LegendZOrder = -1;
            this.npSurface.Location = new System.Drawing.Point(-1, 1);
            this.npSurface.Name = "npSurface";
            this.npSurface.RightMenu = null;
            this.npSurface.ShowCoordinates = true;
            this.npSurface.Size = new System.Drawing.Size(606, 335);
            this.npSurface.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            this.npSurface.TabIndex = 34;
            this.npSurface.Text = "plotSurface2D1";
            this.npSurface.Title = "";
            this.npSurface.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.npSurface.XAxis1 = null;
            this.npSurface.XAxis2 = null;
            this.npSurface.YAxis1 = null;
            this.npSurface.YAxis2 = null;
            // 
            // Scope
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(604, 336);
            this.Controls.Add(this.npSurface);
            this.Name = "Scope";
            this.Text = "Scope";
            this.ResumeLayout(false);

        }

        #endregion

        private NPlot.Windows.PlotSurface2D npSurface;
    }
}